### ISSUE TITLE
High level plan for client app

### ISSUE THREAD

**Issue by mplanchard** [madisonhicks/blob#7]
Let's take a moment to plan for some details about the client application. It is going to be a personal info & blog site (so not multi-user).

In a response to this issue, answer the following questions, remembering that more can be added later, and remembering that there are no incorrect answers:

- [x] what top-level page(s) should exist?
- [x] generally, what should be on each page?
- [x] what blog-post-specific features do we want to support (e.g. images, code highlighting, text formatting, tags, date created, date updated, share links, etc.)?

**Comment by whichking** [comment]
Top-level pages: Just the blog, probably. 

What should be on each page: The blog page should have posts and an informational bar on the side or bottom of the page. Each post should be able to be clicked on to open the individual post in its own page.

What blog-post-specific features should be supported: Images, text formatting, tags, date created, code highlighting, some kind of audio player

**Comment by mplanchard** [comment]
What do you envision to be in the informational bar?

**Comment by whichking** [comment]
No idea. It's not even necessary, I just thought it might be a nice to have a place to put, like, my name or something if I felt like it.

**Comment by mplanchard** [comment]
So it would be a static informational bar? Its content would not be dependent on the blog post(s) currently being viewed?

**Comment by whichking** [comment]
That's right.

**Comment by mplanchard** [comment]
Okay, sounds good.
